# Generated by Django 5.0.4 on 2024-04-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria_Producto',
            new_name='Categoriaproducto',
        ),
    ]
