# Generated by Django 5.0.4 on 2024-04-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_rename_categoria_producto_categoriaproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_id',
        ),
        migrations.DeleteModel(
            name='Categoriaproducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
